-- Returns Hendersonville Police Department incidents where the LPR Used field is set to 
-- Yes. Includes the incident/report number, LPR contact details, arrival and departure 
-- dates, involved party information, company and rental information, all 
-- associated incident narratives, and indicators showing whether the incident 
-- is associated with one or more arrests, including the unique arrest count. The current 
-- query is limited to records created from January 1, 2026 through June 30, 2026.



SELECT
    USI.INSTANCE_ID AS INSTANCE_ID,
    USI.INSTANCE_NUMBER,
    USI.AGENCY_CODE,
    USI.ORG_AGENCY_CODE,
    USI.CREATOR_NAME AS "CREATOR_NAME",
    USI.CREATOR_DATE,
    REC.INCIDENT_ID,
    REC.INC_REPORT_NUMBER AS "INC_REPORT_NUMBER",

    (
        SELECT COUNT(DISTINCT IA.ARR_ARREST_ID)
        FROM TN83.INCIDENT_ARRESTS IA
        WHERE IA.INCSUP_INC_INCIDENT_ID = REC.INCIDENT_ID
    ) AS "ARREST_COUNT",

    CASE
        WHEN EXISTS (
            SELECT 1
            FROM TN83.INCIDENT_ARRESTS IA
            WHERE IA.INCSUP_INC_INCIDENT_ID = REC.INCIDENT_ID
        )
        THEN 'Yes'
        ELSE 'No'
    END AS "HAS_ARREST",

    NARR.SUPP_SEQ AS "NARRATIVE_SUPPLEMENT",
    NARR.NARRATIVE_NUMBER AS "NARRATIVE_NUMBER",
    NARR.NOTE_ID AS "NARRATIVE_NOTE_ID",
    NARR.NARR_TITLE AS "NARRATIVE_TITLE",
    NARR.NARRATIVE AS "NARRATIVE",

    C_0.VALUE AS "HDVL_STR_ARRIVAL_DATE0",
    C_0.VALUE AS "HDVL_STR_ARRIVAL_DATE1",
    C_1.VALUE AS "_HDVL_LPR_CONTACT_DETAILS0",
    C_2.VALUE AS "HDVL_STR_DEPART_DATE0",
    C_2.VALUE AS "HDVL_STR_DEPART_DATE1",
    C_3.VALUE AS "HDVL_STR_INVOLVED0",
    C_4.VALUE AS "HDVL_STR_DAYS_RENTED0",
    C_5.VALUE AS "HDVL_LPR_CONTACT_TYPE_210",
    C_6.VALUE AS "HDVL_LPR_CONTACT_TYPE0",
    C_7.VALUE AS "HDVL_STR_COMPANY_NAME0",
    C_8.VALUE AS "HDVL_LPR_USED0"

FROM TN83.USI_SEARCH_VW USI

INNER JOIN TN83.USI_INCIDENT_FIELDS
    ON USI.INSTANCE_ID = USI_INCIDENT_FIELDS.INSTANCE_ID

INNER JOIN TN83.INCIDENTS REC
    ON USI_INCIDENT_FIELDS.INCIDENT_ID = REC.INCIDENT_ID

LEFT OUTER JOIN TN83.INCIDENT_SUPP_NARRATIVE_VW NARR
    ON NARR.INCIDENT_ID = REC.INCIDENT_ID

LEFT OUTER JOIN TN83.UF_QUERY_DATE_VW C_0
    ON C_0.FIELD_ID = 25
    AND C_0.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_TEXT_VW C_1
    ON C_1.FIELD_ID = 330
    AND C_1.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_DATE_VW C_2
    ON C_2.FIELD_ID = 28
    AND C_2.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_TEXT_VW C_3
    ON C_3.FIELD_ID = 29
    AND C_3.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_TEXT_VW C_4
    ON C_4.FIELD_ID = 27
    AND C_4.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_TEXT_VW C_5
    ON C_5.FIELD_ID = 331
    AND C_5.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_TEXT_VW C_6
    ON C_6.FIELD_ID = 23
    AND C_6.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_TEXT_VW C_7
    ON C_7.FIELD_ID = 26
    AND C_7.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

LEFT OUTER JOIN TN83.UF_QUERY_TEXT_VW C_8
    ON C_8.FIELD_ID = 24
    AND C_8.SCREEN_INSTANCE_ID = USI.INSTANCE_ID

WHERE USI.SCREEN_ID = 5
    AND USI.SCREEN_TYPE_CODE = 'INCIDENTFIELDS'
    AND C_8.VALUE = 'Yes'
    AND USI.CREATOR_DATE >= DATE '2026-01-01'
    AND USI.CREATOR_DATE < DATE '2026-07-01'

ORDER BY
    USI.CREATOR_DATE,
    REC.INC_REPORT_NUMBER,
    NARR.SUPP_SEQ,
    NARR.NARRATIVE_NUMBER
